name: floating_menu_expendable_example
publish_to: 'none'
description: Example app for floating_menu_expendable.
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  floating_menu_expendable:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
