name: floating_menu_expendable
description: "A draggable floating handle that opens a customizable panel (side or vertical)."
version: 1.0.0
homepage: https://github.com/alheekmahlib/floating_menu_expendable
repository: https://github.com/alheekmahlib/floating_menu_expendable
issue_tracker: https://github.com/alheekmahlib/floating_menu_expendable/issues

topics:
  - overlay
  - menu
  - draggable
  - floating-action
  - ui

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


platforms:
  ? linux
  ? windows
  ? web
  ? android
  ? ios
  ? macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
